### ISSUE TITLE
Add information about where the saved images are stored in RAM.

### ISSUE THREAD

**Issue by AntonioND** [AntonioND/gbcam-rev-engineer#1]
Add the location of the big and small pictures that are saved in the cartridge. It's not really related to how the GB camera works, but some people may find it useful.

**Comment by HerrZatacke** [comment]
The "Game Boy Camera discord" has done quite a bit of work documenting it:
https://funtography.online/wiki/Cartridge_RAM

(edit: as a flashable Cartridge PCB is now available for modders, I've started to recreate a ROM which can address the sensor. Much with the help of your document!!! ♥)

**Comment by AntonioND** [comment]
Oh, good to know! I never really cared enough about where the photos were stored, this was just an idea I had, but I never bothered with it. 😅
